### PR TITLE
Add user app support

### PR DESCRIPTION
**Pull request by marralesfios**
Note: I haven't tested it yet!

### CODE REVIEW

**Comment by marralesfios** [comment]
hm, wait
it doesn't use discord.py 🤦
(Edit: Fixed)

**Comment by 00001H** [comment]
it doesn't use discord.py 🤦

**Comment by 00001H** [comment]
It doesn't help that discord.py has `discord`(and `discord.ext`) registered too so

**Comment by gregdan3** [comment]
@00001H This doesn't work. While the change allows you to install the app to your account, none of the commands available- presumably, they are only registered as guild commands, and not also as user commands. 

If you have a system with Docker or Podman, you should be able to `make build up` in the root of the repo so long as your `.env` is set with your needed secrets- double check the project README!

**Pull request merged**
